<?php

namespace Tests\Feature\Shared\Export;

use Spatie\Browsershot\Browsershot;
use Src\Shared\Export\Infrastructure\SpatiePdfExporter;
use Tests\TestCase;

/**
 * Exercises the real spatie/laravel-pdf → DOMPDF path end to end — every
 * other PDF export test in this app (TeacherExportTest, RoleComponent's
 * export tests, etc.) substitutes CapturingPdfExporter to avoid the cost
 * of real rendering, which means none of them ever actually invoked this
 * adapter. This test proves the contract itself: static HTML in, real
 * PDF bytes out, entirely inside the PHP process.
 *
 * spatie/browsershot is no longer a dependency of this project at all
 * (see composer.json) — if config('laravel-pdf.driver') were ever
 * misconfigured back to 'browsershot', resolving that driver would throw
 * immediately (the package class wouldn't exist), so there is no way for
 * this path to silently fall back to a browser-based renderer.
 */
class SpatiePdfExporterTest extends TestCase
{
    public function test_it_renders_real_pdf_bytes_via_the_configured_driver(): void
    {
        $this->assertSame('dompdf', config('laravel-pdf.driver'), 'This test asserts the DOMPDF path specifically.');

        $exporter = new SpatiePdfExporter;

        $response = $exporter->fromHtml(
            '<html><body><h1>Reporte de prueba</h1><p>Acentuación: ñ, á, é, í, ó, ú.</p></body></html>',
            'reporte-prueba.pdf',
        );

        $this->assertSame('application/pdf', $response->headers->get('Content-Type'));
        $this->assertStringContainsString('reporte-prueba.pdf', (string) $response->headers->get('Content-Disposition'));

        ob_start();
        $response->sendContent();
        $pdfBytes = ob_get_clean();

        $this->assertNotEmpty($pdfBytes);
        $this->assertStringStartsWith('%PDF-', $pdfBytes, 'Output must be a real PDF, not an error page or empty stream.');
        $this->assertSame(
            (string) strlen($pdfBytes),
            $response->headers->get('Content-Length'),
            'Content-Length must match the actual generated byte count.',
        );
    }

    public function test_it_does_not_require_browsershot_to_be_installed(): void
    {
        $this->assertFalse(
            class_exists(Browsershot::class),
            'spatie/browsershot must not be a dependency of this project — static reports use DOMPDF only.',
        );
    }
}
